# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oV3zosokmWkghOHVkCQhIpVf1DxGvdJ7
"""

ID=input()
if ID == ID:
     print(ID + '??!')
else:
    print(ID)



A,B,C=map(int,input().split())
# B=int(input())
# C=int(input())

print((A+B)%C)
print(((A%C)+(B%C))%C)
print((A*B)%C)
print(((A%C)*(B%C))%C)

A=int(input())
a,b,c=number = map(int,str(input()))
print(A*c, A*b, A*a, A*c+(A*b)*10+(A*a)*100 ,sep='\n')

